return {
    {
        "nvim-treesitter/nvim-treesitter",
        opts = {
            textobjects = {
                move = {
                    -- goto_next_start = {
                    --     ["]o"] = { query = "@block.inner", desc = "next code block" },
                    -- },
                    -- goto_preivous_start = {
                    --     ["[o"] = { query = "@block.inner", desc = "previous code block" },
                    -- },
                    goto_next_start = { ["]o"] = "@block.inner" },
                    goto_next_end = { ["]O"] = "@block.inner" },
                    goto_previous_start = { ["[o"] = "@block.inner" },
                    goto_previous_end = { ["[O"] = "@block.inner" },
                },
            },
            ensure_installed = {
                "bash",
                "c",
                "html",
                "javascript",
                "json",
                "lua",
                "luadoc",
                "luap",
                "markdown",
                "markdown_inline",
                "python",
                "query",
                "regex",
                "tsx",
                "typescript",
                "vim",
                "vimdoc",
                "yaml",
                "bash",
                "html",
                "css",
                "javascript",
                "json",
                "lua",
                "markdown",
                "markdown_inline",
                "python",
                "vim",
                "yaml",
                "python",
                "julia",
                "r",
            },
        },
    },
}
