#!/usr/bin/env bash

# if [[ $# -eq 1 ]]; then
#     selected=$1
# else
#     selected=$(fd -H -t d -L -i . ~ | fzf)
# fi

selected=$(fd -H -t d -L -i . ~ | fzf)

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)

if [ $(pgrep tmux) ]; then
    # tmux_running=1
    if ! tmux has -t=$selected_name 2>/dev/null; then
        # echo "Session $selected_name does not exist"
        tmux new -ds $selected_name -c $selected
    # else
    #     echo "Session $selected_name exists"
    fi
else
    # tmux_running=0
    # echo "tmux not running"
    tmux new -ds $selected_name -c $selected
fi

if [ "$TMUX" ]; then
    tmux switch -t $selected_name
else
    tmux attach -t $selected_name
fi



