#!/usr/bin/env bash

selected=$({
	tmux list-sessions 2>/dev/null | awk -F: '{print $1}'
    fd -H -t d -L -i . ~ 
} | fzf)

if [[ -z $selected ]]; then
	exit 0
fi

sname=$(basename "$selected" | tr . _)

if ! tmux has -t=$sname 2>/dev/null; then
    tmux new -s "$sname" -n "nvim" -c $selected -d \; send-keys -t "$sname:nvim.1" nvim C-m
fi

tmux switch -t $sname
